### ISSUE TITLE
Dimmable lights

### ISSUE THREAD

**Issue by frmi** [priiduonu/ihcclient#1]
Hi 

Thank you for this great project.

Do you have experience using this to integrate dimmable lights?

I am not familiar with IHC as such but i have managed to integrate it to Home Assistant following your guide, but the dimmable lights seems to be controlled by two outputs, as if i turn one on using using the IHCServer it acts as holding the physical contact.

**Comment by priiduonu** [comment]
Thank You for the kind feedback!

There are different dimmer modules used with IHC. I have the Dimmer 400 UNI modules in my system, driven by 24V output module in a 1-button configuration.

That means, as long as I am pressing the button, the 24V module will provide power for contact `#1` of the dimmer unit and the brightness will rise or fall. When I release the button and press it down again, the brightness will change in the other direction.

When I toggle the button briefly, the light will turn on or off.

For a normal use you do not need more than that. But I found it inconvenient to toggle a single switch in HA to turn the lights on/off or turn it on for the right duration to change the brightness. Unfortunately HA does not have a "momentary" or "pulse" switch function as well as a "hold down" switch function. So I made custom script that can be used to "toggle" the lights on/off by providing power for contact `#1` for 100 ms (should be less than 400 ms).

You can also turn the light off by providing a short pulse to contact `#2`.

Contacts `#3` and `#4` of the dimmer unit can be use as memory - a long pulse (more then 2 s) will save the current brightness level and a short pulse (less than 0.4 s) will recall it. So you can have 2 different levels saved and recalled.

The most annoying thing with (at least the old) IHC dimmer units is - you can not get any feedback if the lights are on or off and you can not set them to arbitrary level.

I think I will properly document my findings and provide the examples in the coming days :-)

**Comment by priiduonu** [comment]
@frmi  - please take a look at the dimmer documentation and examples.

**Comment by frmi** [comment]
Hi @priiduonu,

Thank you for the documentation.

I have given it a read, and i have made it work turning on/off the lights 👍 

I have the 350 CR dimmers, and i am unable to fetch the current state of the light. The IHC Server receives a sequence of On Off on the output. I need to read the documentation on these i guess :)

Have you experienced that the ihc server suddenly becomes unable to communicate with ihc controller?

**Comment by priiduonu** [comment]
1. You can *not* get the dimmer status from the (older) IHC Controller. I do not know about new controllers/dimmers.

2. I have successfully run the IHC Server (along with my IHC Client) 24/7 for 5+ years. Things to check:

- did you experiment with reverting the certain commit in the utils repo (see my docs on installing IHC Server)?
- does the IHC Server web interface stop responding as well?

Maybe completely irrelevant, but I experienced the following some time ago:

- one pushbutton switch was physically jammed for quite some time before I found out
- (after releasing the jammed button) when I was switching the output, originally controlled by the button, from the HA, the IHC Server did not output any running data any more
- I had to reflash the IHC Controller (just downloaded and uploaded again) project file to gt it fully functional again

Note that my IHC Controller constantly flashes some leds (connected to 24V output module) with 0.5s interval, so there is always some traffic present.
